// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhmausltozkxxihzmxsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobWF1c2x0b3preHhpaHpteHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzQ4MDgsImV4cCI6MjA2NDcxMDgwOH0.knAXq6dh_Bv9ums-y7FS-jxDijx1LOK-dBWnLRljNXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);